# Generated By: Claude Code (claude-opus-5-5)
"""List every Gmail filter whose criteria match the message with a given Message-ID.

Each filter's criteria is turned into a Gmail search query, ANDed with
``rfc822msgid:<id>``, and run through messages.list. Gmail's own search engine
decides the match, so no criteria semantics are re-implemented here.
"""

import argparse
import json
import logging
import shutil
import subprocess
import sys
import textwrap
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any

logger = logging.getLogger("find_gmail_filter")

EXIT_SUCCESS = 0
EXIT_ERROR = 1


class GwsError(Exception):
    """gws exited non-zero or returned unparseable output."""


def run_gws(resource_args: list[str], params: dict[str, Any]) -> dict[str, Any]:
    """Run a gws API call and return the parsed JSON response."""
    command = ["gws", *resource_args, "--params", json.dumps(params)]
    logger.debug(f"Running: {command}")
    completed = subprocess.run(command, capture_output=True, text=True)
    if completed.returncode != 0:
        raise GwsError(
            f"{' '.join(resource_args)} failed (exit {completed.returncode}): "
            f"{completed.stderr.strip() or completed.stdout.strip()}"
        )
    try:
        response: dict[str, Any] = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        raise GwsError(f"{' '.join(resource_args)} returned non-JSON: {exc}")
    return response


def size_comparison(criteria: dict[str, Any]) -> str | None:
    """Return "larger" or "smaller" when the filter has a usable size criterion."""
    if criteria.get("size") and criteria.get("sizeComparison") in ("larger", "smaller"):
        return str(criteria["sizeComparison"])
    return None


def criteria_to_query(criteria: dict[str, Any]) -> str:
    """Build the Gmail search query equivalent of a filter's FilterCriteria."""
    terms = []
    for field, operator in (("from", "from:"), ("to", "to:"), ("subject", "subject:")):
        if criteria.get(field):
            terms.append(f"{operator}({criteria[field]})")
    if criteria.get("query"):
        terms.append(f"({criteria['query']})")
    # ponytail: API doc says "not matching the specified query", so -(...).
    # Gmail's UI renders "Doesn't have" as -{...} (any word excludes); unverified
    # which one the filter engine applies when negatedQuery has several words.
    if criteria.get("negatedQuery"):
        terms.append(f"-({criteria['negatedQuery']})")
    if criteria.get("hasAttachment"):
        terms.append("has:attachment")
    if criteria.get("excludeChats"):
        terms.append("-in:chats")
    if comparison := size_comparison(criteria):
        terms.append(f"{comparison}:{criteria['size']}")
    return " ".join(terms)


# Labels as Gmail's filter editor shows them, so output reads like the UI.
FIELD_LABELS = (
    ("from", "From"),
    ("to", "To"),
    ("subject", "Subject"),
    ("query", "Has the words"),
    ("negatedQuery", "Doesn't have"),
)
# "Has attachment" and "Excludes chats" are the longest; +2 for ": ".
LABEL_WIDTH = len("Has attachment") + 2


# System labels a filter adds or removes to express the editor's checkboxes.
# ponytail: wording recalled from Gmail's filter editor, not checked against it.
ADDED_SYSTEM_LABELS = {
    "STARRED": "Star it",
    "TRASH": "Delete it",
    "IMPORTANT": "Always mark it as important",
}
REMOVED_SYSTEM_LABELS = {
    "INBOX": "Skip the Inbox (archive it)",
    "UNREAD": "Mark as read",
    "SPAM": "Never send it to Spam",
    "IMPORTANT": "Never mark it as important",
}


def criteria_rows(criteria: dict[str, Any]) -> list[tuple[str, str]]:
    """(label, value) rows for the criteria a filter sets."""
    rows = [
        (label, criteria[field]) for field, label in FIELD_LABELS if criteria.get(field)
    ]
    if comparison := size_comparison(criteria):
        rows.append(("Size", f"{comparison} than {criteria['size']} bytes"))
    if criteria.get("hasAttachment"):
        rows.append(("Has attachment", "yes"))
    if criteria.get("excludeChats"):
        rows.append(("Excludes chats", "yes"))
    return rows


def describe_actions(action: dict[str, Any], label_names: dict[str, str]) -> list[str]:
    """One line per side effect of a filter, user label IDs resolved to names."""
    lines = [
        REMOVED_SYSTEM_LABELS.get(label_id)
        or f"Remove label: {label_names.get(label_id, label_id)}"
        for label_id in action.get("removeLabelIds", [])
    ]
    for label_id in action.get("addLabelIds", []):
        if label_id in ADDED_SYSTEM_LABELS:
            lines.append(ADDED_SYSTEM_LABELS[label_id])
        elif label_id.startswith("CATEGORY_"):
            category = label_id.removeprefix("CATEGORY_").title()
            lines.append(f"Categorize as: {category}")
        else:
            lines.append(f"Apply label: {label_names.get(label_id, label_id)}")
    if action.get("forward"):
        lines.append(f"Forward to: {action['forward']}")
    return lines


def format_filter(
    number: int,
    gmail_filter: dict[str, Any],
    label_names: dict[str, str],
    *,
    width: int,
) -> str:
    """Render one filter as a numbered block: criteria, then actions, one per line.

    Long values wrap under the value column instead of back to column 0.
    """
    rows = criteria_rows(gmail_filter.get("criteria", {}))
    actions = describe_actions(gmail_filter.get("action", {}), label_names)
    rows += [
        ("Actions" if index == 0 else "", text)
        for index, text in enumerate(actions or ["(none)"])
    ]
    indent = " " * 4
    lines = [f"Filter {number}"]
    for label, value in rows:
        lines.append(
            textwrap.fill(
                str(value),
                width=max(width, len(indent) + LABEL_WIDTH + 20),
                initial_indent=f"{indent}{label + ':' if label else '':<{LABEL_WIDTH}}",
                subsequent_indent=indent + " " * LABEL_WIDTH,
                break_long_words=False,
                break_on_hyphens=False,
            )
        )
    return "\n".join(lines)


def fetch_label_names() -> dict[str, str]:
    """Map label ID to display name. labels.list is not paginated."""
    response = run_gws(["gmail", "users", "labels", "list"], {"userId": "me"})
    return {label["id"]: label["name"] for label in response.get("labels", [])}


def message_matches(message_id: str, query: str) -> bool:
    """True when the message with this Message-ID matches the search query."""
    response = run_gws(
        ["gmail", "users", "messages", "list"],
        {
            "userId": "me",
            "q": f"rfc822msgid:{message_id}" + (f" ({query})" if query else ""),
            "maxResults": 1,
            # Filters that trash or mark spam move the message out of the default scope.
            "includeSpamTrash": True,
        },
    )
    return bool(response.get("messages"))


def find_matching_filters(message_id: str, *, jobs: int) -> list[dict[str, Any]]:
    """Return every filter (criteria and action) matching the message, in API order."""
    logger.info(f"Looking up message {message_id}")
    if not message_matches(message_id, ""):
        raise GwsError(f"No message found with Message-ID {message_id}")
    logger.info("Message found, fetching filters")
    response = run_gws(
        ["gmail", "users", "settings", "filters", "list"], {"userId": "me"}
    )
    # filters.list is not paginated; the key is absent when there are no filters.
    filters = response.get("filter", [])
    queries = []
    searchable_filters = []
    for gmail_filter in filters:
        query = criteria_to_query(gmail_filter.get("criteria", {}))
        logger.debug(f"Filter {gmail_filter.get('id')}: {query}")
        if not query:
            logger.warning(f"Filter {gmail_filter.get('id')} has no criteria, skipped")
            continue
        queries.append(query)
        searchable_filters.append(gmail_filter)
    logger.info(f"Checking {len(queries)} filters with {jobs} parallel jobs")
    # Threads, not processes: each worker just waits on a gws subprocess.
    executor = ThreadPoolExecutor(max_workers=jobs)
    matches = []
    progress_interval = max(1, len(queries) // 10)
    try:
        results = executor.map(lambda q: message_matches(message_id, q), queries)
        # map yields in submission order, so progress can trail by up to `jobs`.
        for checked, (gmail_filter, matched) in enumerate(
            zip(searchable_filters, results), start=1
        ):
            if matched:
                matches.append(gmail_filter)
            if checked % progress_interval == 0 and checked < len(queries):
                logger.info(
                    f"Checked {checked}/{len(queries)} filters, "
                    f"{len(matches)} matched so far"
                )
    finally:
        # On the first failure (e.g. expired auth) drop queued calls instead of
        # running the rest of hundreds of filters before reporting it.
        executor.shutdown(cancel_futures=True)
    logger.info(f"Matched {len(matches)} of {len(queries)} filters")
    return matches


def positive_int(value: str) -> int:
    number = int(value)
    if number < 1:
        raise argparse.ArgumentTypeError(f"must be at least 1, got {number}")
    return number


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="find-gmail-filter",
        description="List Gmail filters that match a message, by Message-ID.",
    )
    parser.add_argument("message_id", help="Message-ID header value, <> optional")
    parser.add_argument("--debug", action="store_true", help="enable debug output")
    parser.add_argument(
        "-q", "--quiet", action="store_true", help="suppress non-essential output"
    )
    parser.add_argument("--log-file", type=Path, help="write log output to file")
    parser.add_argument(
        "-j",
        "--jobs",
        type=positive_int,
        default=8,
        help="parallel Gmail searches (default: 8)",
    )
    args = parser.parse_args(argv)

    if args.debug:
        level = logging.DEBUG
    elif args.quiet:
        level = logging.WARNING
    else:
        level = logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
        **(
            {"filename": args.log_file.expanduser().resolve(), "filemode": "a"}
            if args.log_file
            else {"stream": sys.stderr}
        ),
    )

    message_id = args.message_id.strip().removeprefix("<").removesuffix(">")
    try:
        matches = find_matching_filters(message_id, jobs=args.jobs)
        # Only needed to name labels in actions; skip the call when nothing matched.
        label_names = fetch_label_names() if matches else {}
    except GwsError as exc:
        logger.error(str(exc))
        return EXIT_ERROR
    width = shutil.get_terminal_size().columns
    blocks = [
        format_filter(number, gmail_filter, label_names, width=width)
        for number, gmail_filter in enumerate(matches, start=1)
    ]
    if blocks:
        print("\n\n".join(blocks))
    return EXIT_SUCCESS


if __name__ == "__main__":
    sys.exit(main())
