# Generated By: Claude Code (claude-opus-5-5)
import json
import subprocess
from typing import Any
from unittest.mock import patch

import pytest

from find_gmail_filter import __main__ as cli

MESSAGE_ID = "abc123@mail.example.com"

FILTERS = {
    "filter": [
        {"id": "f1", "criteria": {"from": "alerts@example.com"}},
        {
            "id": "f2",
            "criteria": {"subject": "weekly report"},
            "action": {"removeLabelIds": ["INBOX"], "addLabelIds": ["Label_7"]},
        },
        {"id": "f3", "criteria": {"query": "list:dev.example.com"}},
        {"id": "f4", "criteria": {}},
    ]
}


def test_criteria_to_query_all_fields() -> None:
    criteria = {
        "from": "a@x.com",
        "to": "me",
        "subject": "hi there",
        "query": "foo OR bar",
        "negatedQuery": "baz",
        "hasAttachment": True,
        "excludeChats": True,
        "size": 1000,
        "sizeComparison": "larger",
    }
    assert cli.criteria_to_query(criteria) == (
        "from:(a@x.com) to:(me) subject:(hi there) (foo OR bar) -(baz) "
        "has:attachment -in:chats larger:1000"
    )


def test_criteria_to_query_ignores_unspecified_size() -> None:
    criteria = {"size": 1000, "sizeComparison": "unspecified", "from": "a"}
    assert cli.criteria_to_query(criteria) == "from:(a)"


def fake_gmail(matching_queries: set[str], *, message_exists: bool = True) -> Any:
    """Stand-in for run_gws: messages.list matches only the given filter queries."""

    def run(resource_args: list[str], params: dict[str, Any]) -> dict[str, Any]:
        if resource_args[-2:] == ["filters", "list"]:
            return FILTERS
        if resource_args[-2:] == ["labels", "list"]:
            return {"labels": [{"id": "Label_7", "name": "Reports"}]}
        assert params["includeSpamTrash"] is True
        prefix = f"rfc822msgid:{MESSAGE_ID}"
        if params["q"] == prefix:
            return {"messages": [{"id": "1"}]} if message_exists else {}
        inner = params["q"].removeprefix(prefix + " (").removesuffix(")")
        return {"messages": [{"id": "1"}]} if inner in matching_queries else {}

    return run


@pytest.mark.parametrize("jobs", [1, 4])
def test_find_matching_filters_returns_every_match_in_order(
    jobs: int, caplog: pytest.LogCaptureFixture
) -> None:
    matching = {"from:(alerts@example.com)", "(list:dev.example.com)"}
    caplog.set_level("INFO", logger="find_gmail_filter")
    with patch.object(cli, "run_gws", side_effect=fake_gmail(matching)):
        assert cli.find_matching_filters(MESSAGE_ID, jobs=jobs) == [
            FILTERS["filter"][0],
            FILTERS["filter"][2],
        ]
    assert f"Looking up message {MESSAGE_ID}" in caplog.text
    assert "Checked 1/3 filters, 1 matched so far" in caplog.text
    assert "Checked 3/3" not in caplog.text
    assert "Matched 2 of 3 filters" in caplog.text


def test_find_matching_filters_missing_message_raises() -> None:
    with patch.object(
        cli, "run_gws", side_effect=fake_gmail(set(), message_exists=False)
    ):
        with pytest.raises(cli.GwsError, match="No message found"):
            cli.find_matching_filters(MESSAGE_ID, jobs=1)


def test_main_rejects_zero_jobs() -> None:
    with pytest.raises(SystemExit):
        cli.main([MESSAGE_ID, "--jobs", "0"])


def test_main_strips_brackets_and_prints_matches(
    capsys: pytest.CaptureFixture[str],
) -> None:
    with patch.object(
        cli, "run_gws", side_effect=fake_gmail({"subject:(weekly report)"})
    ):
        assert cli.main([f"<{MESSAGE_ID}>"]) == cli.EXIT_SUCCESS
    assert capsys.readouterr().out == (
        "Filter 1\n"
        "    Subject:        weekly report\n"
        "    Actions:        Skip the Inbox (archive it)\n"
        "                    Apply label: Reports\n"
    )


def test_main_prints_nothing_without_matches(
    capsys: pytest.CaptureFixture[str],
) -> None:
    with patch.object(cli, "run_gws", side_effect=fake_gmail(set())):
        assert cli.main([MESSAGE_ID]) == cli.EXIT_SUCCESS
    assert capsys.readouterr().out == ""


def test_format_filter_wraps_under_value_column() -> None:
    gmail_filter = {
        "criteria": {
            "from": "a@x.com",
            "query": "list:one.example.com OR list:two.example.com OR list:three",
            "size": 5000,
            "sizeComparison": "smaller",
            "hasAttachment": True,
            "excludeChats": True,
        }
    }
    assert cli.format_filter(2, gmail_filter, {}, width=60) == (
        "Filter 2\n"
        "    From:           a@x.com\n"
        "    Has the words:  list:one.example.com OR\n"
        "                    list:two.example.com OR list:three\n"
        "    Size:           smaller than 5000 bytes\n"
        "    Has attachment: yes\n"
        "    Excludes chats: yes\n"
        "    Actions:        (none)"
    )


def test_describe_actions_names_every_side_effect() -> None:
    action = {
        "removeLabelIds": ["INBOX", "UNREAD", "SPAM", "IMPORTANT", "Label_9"],
        "addLabelIds": [
            "STARRED",
            "TRASH",
            "CATEGORY_PROMOTIONS",
            "Label_1",
            "Label_X",
        ],
        "forward": "me@elsewhere.example",
    }
    label_names = {"Label_1": "Work/Alerts", "Label_9": "Old"}
    assert cli.describe_actions(action, label_names) == [
        "Skip the Inbox (archive it)",
        "Mark as read",
        "Never send it to Spam",
        "Never mark it as important",
        "Remove label: Old",
        "Star it",
        "Delete it",
        "Categorize as: Promotions",
        "Apply label: Work/Alerts",
        "Apply label: Label_X",
        "Forward to: me@elsewhere.example",
    ]


def test_main_reports_gws_failure() -> None:
    failed = subprocess.CompletedProcess(
        args=[], returncode=1, stdout="", stderr="boom"
    )
    with patch.object(cli.subprocess, "run", return_value=failed):
        assert cli.main([MESSAGE_ID]) == cli.EXIT_ERROR


def test_run_gws_passes_params_as_json() -> None:
    ok = subprocess.CompletedProcess(
        args=[], returncode=0, stdout='{"a": 1}', stderr=""
    )
    with patch.object(cli.subprocess, "run", return_value=ok) as mock_run:
        assert cli.run_gws(["gmail", "x"], {"userId": "me"}) == {"a": 1}
    command = mock_run.call_args.args[0]
    assert command[:2] == ["gws", "gmail"]
    assert json.loads(command[-1]) == {"userId": "me"}


def test_run_gws_non_json_raises() -> None:
    bad = subprocess.CompletedProcess(args=[], returncode=0, stdout="nope", stderr="")
    with patch.object(cli.subprocess, "run", return_value=bad):
        with pytest.raises(cli.GwsError, match="non-JSON"):
            cli.run_gws(["gmail"], {})
